server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    types {
        text/html                   html htm;
        text/css                    css;
        application/javascript      js mjs;
        application/json            json;
        image/png                   png;
        image/jpeg                  jpg jpeg;
        image/svg+xml               svg;
        image/webp                  webp;
        font/woff2                  woff2;
        font/woff                   woff;
        application/octet-stream    bin;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}